blog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [path('', views.PostView.as_view(), name='home'),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>', views.AddComments.as_view(), name='add_comments'),
               path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_like'),
               path('<int:pk>/del_likes/', views.DelLike.as_view(), name='del_like'),
               ]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_view.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),

]

blog/models.py
from django.db import models


class Post(models.Model):
    '''данные в посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст записи')
    author = models.CharField('автор', max_length=100)
    date = models.DateField('Дата публикации')
    image = models.ImageField('Изображение', upload_to='image/')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    '''Класс комментариев'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self. name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Likes
from .form import CommentsForm


class PostView(View):
    '''вывод записей'''

    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    '''Отдельная страница записи'''

    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    '''Добавление комментариев'''

    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, post_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.post_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')


class DelLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Здравствуйте, {username}, вы успешно зарегистрировались')
            return redirect('home')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required()
def profile(request):
    return render(request, 'registration/profile.html')

templates/blog/base.html
{% load static %}
<html >
<head>
	<title>Мой блог</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

	<link rel="shortcut icon" href="css/images/favicon.ico" />
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap" rel="stylesheet">

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<div class="menu-wrap">
				<ul>
			    	<li><a href="/" class="">Главная</a></li>
			    	<li><a href="/admin">Админ панель</a></li>
				</ul>
			</div>
			<div class="auth-wrap">
				<ul>
					{% if user.is_authenticated %}
						<li class="sign-up-btn"><a href="/profile">Профиль</a></li>
					{% else %}
						<li class="sign-up-btn"><a href="/register">Создать аккаунт</a></li>
						<li class=""><a href="/login">Войти</a></li>
					{% endif %}
				</ul>
			</div>
		</div>

		<div id="main">
			<div class="container">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert{{message.tags}}">{{message}}</div>
					{% endfor %}
				{% endif %}
			</div>
			{% block content %}
			{% endblock %}

		</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>

templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div id="content" class="left">
				<div class="projects">
					<h3>Записи</h3>
					{% for post in post_list  %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ post.image.url }}" alt="" height="150px" width = "200px" /></a>
						</div>
						<div class="text left">
							<h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
							<p> {{ post.description }}</p>
							<p>Автор: {{ post.author }} </p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>
{% endblock %}

templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ post.title }}</h3>
                    <p align="center">
                        <img src =" {{ post.image.url }}" width="100%"/>
                    </p>
					<div class="item">
						<div class="post-page-text">
							<p  text-align="center" font-size="30px"> {{ post.description }}</p>
							<p>Автор: {{ post.author }} </p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>
			<div class="likes-dislikes">
				<br>
				<p>Понравилось: {{ post.likes_set.all.count }}</p>
				<br>
				<a href="{% url 'add_like' post.id %}">Нравится</a>
				<a href="{% url 'del_like' post.id %}">Не нравится</a>
			</div>
			<div class="form-comment">
				<h3>Оставить комментарий</h3>
				<div>
					<form action="{% url 'add_comments' post.id %}" method="post">
						{% csrf_token %}
						<div>
							<label>Ваш комментарий</label>
							<textarea  name="text_comments"></textarea>
						</div>
						<div>
							<label>Ваше имя</label>
							<input type="text" name="name">
						</div>
						<div>
							<label>Ваш email</label>
							<input type="email" name="email">
						</div>
						<div>
							<input type="submit">
						</div>
					</form>
				</div>
			</div>
			<div>
				{% for comment in post.comments_set.all %}
				<div class="view-comment">
					<h4>{{ comment.name }}</h4>
					<p>
						{{ comment.text_comments }}
					</p>
				</div>
				{% endfor %}
			</div>
			<div class="cl">&nbsp;</div>
		</div>
	{% endblock %}